Update to gdnative 0.10.1
setzer22/godot-egui pull request #34
Opened 2022-09-03 17:00 UTC by Bromeon

Updates to latest `gdnative` release and migrates to the new `#[method]` syntax.

2022-09-06 15:04 UTC, setzer22 requested changes
Looks good! Thanks for taking care of this :) 

Left a few very minor comments but it looks good. I see there were no major changes other than the new `#[method]` syntax which IMO looks better now :+1:

2022-09-06 15:04 UTC, setzer22 commented on example_project/Cargo.toml
> +#gdnative = { git = "https://github.com/godot-rust/godot-rust.git", branch = "master" }
Leftover comment?

2022-09-06 15:04 UTC, setzer22 commented on godot_egui/src/lib.rs
> +            .with_hint(gdnative::export::hint::StringHint::File(EnumHint::new(vec![
Is there a reason for the fully-qualified `gdnative::export::hint::StringHint::File`? Looks a bit verbose, and the other hint types (`FloatHint` and `RangeHint`) are still imported in the `use` statement above.

2022-09-06 15:49 UTC, Bromeon commented on example_project/Cargo.toml
> +#gdnative = { git = "https://github.com/godot-rust/godot-rust.git", branch = "master" }
That was actually left on purpose since I may work on API adjustments prior to crates.io releases, but I can gladly remove this if you prefer! :)

Is the idea more to have a "in-dev" godot-egui with cutting edge stuff, or rather stable and only dependent on crates.io versions?

2022-09-06 15:52 UTC, Bromeon commented on godot_egui/src/lib.rs
> +            .with_hint(gdnative::export::hint::StringHint::File(EnumHint::new(vec![
Yes, the reason is that this builder is feature-gated by `#[cfg(feature = "theme_support")]`. So if you import `StringHint` at the beginning of the file, you'll get warnings of unused import half of the time.

An alternative to fully qualified syntax would be to add a local block:
```rs
#[cfg(feature = "theme_support")]
{
    use gdnative::export::hint::StringHint;

    builder
       .property::<String>("EguiTheme")
       ...
}
```

Or, turn off the warning at the `use` declaration (haven't tried that).

2022-09-07 11:21 UTC, setzer22 commented on godot_egui/src/lib.rs
> +            .with_hint(gdnative::export::hint::StringHint::File(EnumHint::new(vec![
Oh, I see what you mean! In that case I don't think there is a problem with the current approach :smile: We can keep it as-is

2022-09-07 11:23 UTC, setzer22 commented on example_project/Cargo.toml
> +#gdnative = { git = "https://github.com/godot-rust/godot-rust.git", branch = "master" }
> Is the idea more to have a "in-dev" godot-egui with cutting edge stuff, or rather stable and only dependent on crates.io versions?

That's a very good question. I'm on the `master` branch of godot-rust more often than not, so offering a version that tracks the master branch (with some inevitable lag) may appeal to others as well.

I don't mind keeping the comment as long as it's intended :+1:

2022-09-07 11:24 UTC, setzer22 approved these changes

2023-04-02 09:29 UTC, closed without merging